### ISSUE TITLE
Some songs don't have a lyric to them 

### ISSUE THREAD

**Issue by Grimfoxy19883** [Weeb-API/docs#1]
{
  "error": "Failed"
}
this happens when i try to get lyrics From a song on Genius

**Comment by Grimfoxy19883** [comment]
This only happens on certain songs

**Comment by Grimfoxy19883** [comment]
error i get
    validator: 's.literal(V)',
      given: '[Intro: DJ Kay Slay & \n' +
        'Sheek Louch\n' +
        ']\n' +
        'Trackateering Music\n' +
        "Man, y'all did it with this one here, y'all\n" +
        `People love to use that quote, "I'm doin' it for the culture"\n` +
        "But what culture is that that you're talking about?\n" +
        'The one that you claim as a hip-hop artist\n' +
        "But won't do the research on hip-hop history\n" +
        'Or the one where you disrespect, disconnect\n' +
        'And disregard the founding fathers?\n' +
        "But you know what? Whatever it is, it don't even matter\n" +
        "'Cause as long as I'm alive\n" +
        "I'ma show and prove where this culture came from\n" +
        "And what it's really all about\n" +
        '\n' +
        'I got you, my nigga, yo, ayo\n' +
        '\n' +
        '[Verse 1: Sheek Louch]\n' +
        "Count to ten and then come in shootin'\n" +
        'Fuck peace, Silverback the new Huey Newton\n' +
        "I feel it, it's in the air, white cop with a stare\n" +
        "New judge in the chair, this shit hittin' the fan\n" +
        "But me, I'ma be smart and legalize my shit\n" +
        "And I ain't leavin' the house without that in my hand\n" +
        "And it ain't only the cops, it's niggas on your block\n" +
        "That talk like a lil' bitch and act like they your man\n" +
        '\n' +
        '[Verse 2: Styles P]\n' +
        "Somethin' like Kris Parker, my Uzi weigh a ton\n" +
        "Hundred niggas on the track, then you know I'll be the one\n" +
        'To tell niggas to suck cock, run and get a gun\n' +
        "It's old P, new P, prob'ly layin' in the sun\n" +
        "Prob'ly on a P.I., if I call you king\n" +
        "I ain't talkin' 'bout rap, nigga, that status go to B.I\n" +
        'You can fuck around and get burnt like a C.I\n' +
        'More bars than jail, nigga, who tryna get a V.I?[Verse 3: Dave East]\n' +
        'You dealing with stock owners, conversation with stockbrokers\n' +
        "Make a call for coco, smokin' dope from my crop grower\n" +
        'The block know us, kush got a funky sock odor\n' +
        'How could you not notice? I come from that rock culture (Rock)\n' +
        'Star of the squad but they cannot coach (At all)\n' +
        'Louis Vuitton holster, this for my niggas in the cell\n' +
        'And on they wall, they got a Nicki Minaj poster\n' +
        "The talk's over, no drive-by's, we walked over\n" +
        '\n' +
        '[Verse 4: KXNG Crooked]\n' +
        'COB bandana tied to the end of the AR\n' +
        "Iller than they are, rhymes so sick, give 'em the day off\n" +
        'This is the chaos, Nicolas Cage, face off\n' +
        "The dark knight, I make it a dark night when I'm gettin' that K off\n" +
        'Better than whoever done it, even officers better run it\n' +
        "With the drum, I got a technique that'll give twelve a hundred\n" +
        'Now the tables turn, to whom it may concern\n' +
        'I used to control more shooters than David Stern\n' +
        'With Lucifer, hater burn\n' +
        '\n' +
        '[Verse 5: Black Thought]\n' +
        'Yo, I was in the park spray-painting on the platform\n' +
        'Patent leather top ten, Space Invader hats on\n' +
        "Eighty something, I've been a threat for that long\n" +
        'Where a lot of people get poked up and clapped on\n' +
        'My job really putting on for the city\n' +
        'You get popped like a wheelie for saying some old silly shit\n' +
        "Tell me it'll be safer to say it in Swahili\n" +
        'They be wheeling you away if you say it in South Philly[Verse 6: Conway the Machine]\n' +
        "Look, thirty shots, I'm shootin' to peel his top\n" +
        "When them niggas sending shots, they shootin' to get the spot\n" +
        "That I'm in, nigga (Hahaha)\n" +
        'You know what it is when I spin the block (Ah)\n' +
        "Uppin' this Draco, the witness is still in shock (Brrr!)\n" +
        "Fluffin' a brick of this yayo, I tilt the pot (Whip)\n" +
        "Tuckin' this fifth, you play with me, you getting shot (Boom, boom, boom, boom)\n" +
        'Yeah, niggas still waiting for me to drop (Uh-huh)\n' +
        'I robbed niggas for they base and sold easy rock\n' +
        '\n' +
        '[Verse 7: Raekwon]\n' +
        '\n' +
        'Fur coats and magnums\n' +
        '\n' +
        'Come through the hall with the big blammers\n' +
        'Bentaygas parked, let me handle this\n' +
        "Jewelry that's flashy, jeans is a thousand, we slick nasty\n" +
        'Pull out a hundred in your housing\n' +
        "Yeah, it's raw lingo when the king go\n" +
        'Dutch link, nuts big as shit, taste the rainbow (Ayo, yo!)\n' +
        'Put your paper up and threaten shit\n' +
        'Or tie something up, send some messages\n' +
        '\n' +
        '[Verse 8: Ghostface Killah]\n' +
        'Ayo, ayo, I used to tell a maid, "Sunny side up"\n' +
        'Basement, a chainsaw, money tied up\n' +
        "Paper bag over his head, tell 'em come on, let the cries out\n" +
        'Wave a whole chicken by his legs near the crotch smells\n' +
        'Sweating bullets in the tip, blow torching his flesh\n' +
        'I seen his face melt, drip gooey shit on his chest\n' +
        'Watch this motherfucker beg for mercy\n' +
        'Shoulda let his wiz suck my dick for the time he jerked me[Verse 9: Inspectah Deck]\n' +
        'The soldier I rolls with the coldest clique\n' +
        'Call me prototype, never had a mold to fit\n' +
        'My clothes is dipped, my bros is lit\n' +
        'Only time you been sick is when the COVID hit\n' +
        "Better get in line, I chop the bass like I'm pitching dimes\n" +
        'Code name Coffee Bean how I hit the grind\n' +
        'Precision design, exquisite with the vivid shine\n' +
        "I'm like a European watch on a different time\n" +
        '\n' +
        '[Verse 10: Papoose]\n' +
        'I used to run around with a MAC-10\n' +
        'Back when I was 20 years old, that was back then (30)\n' +
        '30 clip in the 40, move yayo like 50\n' +
        'Man, I hustle like Nip in the Rolling 60s\n' +
        "I was born in the 70's, grew up in the 80's\n" +
        'Got the MAC-90, then I went crazy\n' +
        "Do the mathematics, y'all can't compete (100)\n" +
        "All by myself, I'm 100 deep\n" +
        '\n' +
        '[Verse 11: Loaded Lux]\n' +
        'I was on the first 50, now the powers at a dollar\n' +
        'Politician pushing tracks in it, mayor, I president in it\n' +
        "Til it's humbling, think you grounded and get punished\n" +
        'This the second time Slay needed my two cents to keep it a hundred\n' +
        'How you want it? Fake and be a martyr for this matrix?\n' +
        'They gon turn up the AC then charge you for the blankets\n' +
        'Lux verse mean, got you stuck standing there\n' +
        'Like you at a stop sign waiting for it to turn green, what you mean?\n' +
        '\n' +
        '[Verse 12: AZ]\n' +
        'My soul is never for sale\n' +
        "My youngin' just did a twelve, he home, he ringing bells\n" +
        'Wish him well, me and mines on different times\n' +
        "Decline from nigga crimes, I'm fine just spitting rhymes\n" +
        'Read the signs, body language is loud\n' +
        "Cowards hang with the crowd, I ain't never changing my style\n" +
        'Then and now, before that was all that\n' +
        'Fall back, official is what you call that\n' +
        '\n' +
        '[Verse 13: Bun B]\n' +
        'I be that Third Coast legend, Dirty South icon\n' +
        "Shuttin' shit down, soon as they cut my mic on\n" +
        'From the first bar down to the last syllable\n' +
        'Niggas that thought they were immortal find out they killable\n' +
        "Once I see blood, I'm like a Great White\n" +
        "Catch you slippin' on a late night and it's no bark, straight bite\n" +
        'Watch you bleed out as reality starts to sink in\n' +
        'You tried the Triple OG (Bitch) what was you thinking?\n' +
        '\n' +
        '[Verse 14: Fred the Godson]\n' +
        "I give the coke to your crew, the butter's crazy\n" +
        'Fallopian tube, just cut it baby\n' +
        'Gordo butterfly collar cover the Cubans\n' +
        "She need pads like Ewing, I hope you know what you doin' (Look)\n" +
        'Some paid 4-5 serious\n' +
        'I come through, 4-5, serious\n' +
        'Slay got me Shade 45 Sirius\n' +
        'Gold frame shades 45, Siri\n' +
        '\n' +
        '[Verse 15: Jim Jones]\n' +
        'I used to be up in a tunnel like a hundred deep\n' +
        `Screamin', "Nine Trey, Su-Woo" with a bunch of Bs\n` +
        'Never tied up shoes, but every night we would run the streets\n' +
        "Nigga, fuck growlin', it was nights I heard my stomach speak\n" +
        "Then I started pumpin' that bass like they done a beat\n" +
        "Never let shit slide 'cause they might think somethin' sweet\n" +
        "Nigga, it's July, shots get hot like summer heat\n" +
        'When I pop up, niggas turn vegan, they never wanted beef\n' +
        '\n' +
        '[Verse 16: Ransom]\n' +
        'I know these streets with my eyes closed, so my worst fear is to die slow\n' +
        "Lie low, 'cause in '05 you flipped the five-o\n" +
        "And I know, 'cause if Alpo did it to Rich\n" +
        "For some bricks, word to Flex, he had no reason to lie, po'\n" +
        "Aight though, we ain't gotta dwell on the past\n" +
        "Devilish laugh, arrow spins I'm ahead of the crash\n" +
        'Better to clash, when you handle your beef, settle it fast\n' +
        'Metal in mask but still keep an elegant class\n' +
        '\n' +
        '[Verse 17: Rah Digga]\n' +
        'Who the greatest all time? Where them niggas reside?\n' +
        'I seen all fifty names, man them niggas done lied\n' +
        'I take the first forty-eight, make them niggas retire\n' +
        'Last two we could joust, make them niggas my squad\n' +
        "Fuck them, let's see how the ladies fare\n" +
        "Swerve on these bitches like I'm settin' my baby hair\n" +
        "They feel a type way, but they never gon' take it there\n" +
        "They tryna keep it cute 'cause they know that it's safer there\n" +
        "They wouldn't dare\n" +
        '\n' +
        '[Verse 18: Billy Danze]\n' +
        "I can't explain what I dealt with\n" +
        'Know it was all weak and creep and stealth shit\n' +
        'When I come from under the belt with a metal shit\n' +
        "Forever Brownsville, no, I never felt shit (You're as cold as ice)\n" +
        'I still got that real world charm, nigga, be alarmed\n' +
        'Body armor on, warmer in my palm (NYC)\n' +
        'Where you get the storm before the calm\n' +
        'OG and we treat it like Vietnam\n' +
        '\n' +
        '[Verse 19: Lil Fame]\n' +
        'My generation drank forty ounces of Old English to ease the pain\n' +
        "Y'all niggas drink White Claws, nigga, we ain't the same (kahm-kahm)\n" +
        "It's curfew whenever I come through (kahm-kahm)\n" +
        "Kill the fuckery, them niggas can't fuck with me (come on!)\n" +
        "I'm really 'bout it in the war\n" +
        "Taxiderm' your bitch head, mount it on the wall (it's M.O.)\n" +
        "Throw it up, nigga, we stand tall (it's M.O.)\n" +
        "You know what the fuck we stand for, it's M.O\n" +
        '\n' +
        '[Verse 20: Trae the Truth]\n' +
        'Too many niggas in here, but never follow the script\n' +
        "It's movie time, release the clip and have 'em doin' a flip\n" +
        'Off-white Virgil, need a whip with the interior Crip\n' +
        'On any given goal to slide, nigga, minus the slip\n' +
        "Checkin' niggas outta line, like it ain't nothin' to skip\n" +
        "Step in my section trying to flex and end up gettin' you stripped\n" +
        'Too many niggas watered down, might go to sinking they ship\n' +
        "And if it's beef, I cut the trip, I never pull up and dip\n" +
        "It's Precious season, nigga\n" +
        '\n' +
        '[Verse 21: Joell Ortiz]\n' +
        "Walkin' in the storm, my face had the hatred in it\n" +
        'Mons had the colorful money with the staples in it\n' +
        'Grew up street and I stay committed (Yeah)\n' +
        "Movin' white back and forth over green like table tennis\n" +
        "Guap was pourin' in, my Glock was roarin'\n" +
        'At nineteen, shots hit you like hydroxychloroquine\n' +
        "I'm still forty with the forty close\n" +
        "In the 840 playin' new E-40 with some horny hoes\n" +
        '\n' +
        '[Verse 22: Lord Tariq]\n' +
        "(Yeah) Finally, y'all been waiting\n" +
        'To hear a verse for the economy stimulation\n' +
        'With Bible verses forsaken and tribal authorization\n' +
        "We marchin' as we awaken the mobsters across the nation\n" +
        'Ask doubles next to ride\n' +
        'The show gun with Shogun to testify\n' +
        "To show somethin', we hold somethin' that electrifies\n" +
        'N-1 L-B, no one left behind, pause it\n' +
        '\n' +
        '[Verse 23: Cory Gunz]\n' +
        'Where I grew up in the world of Pop to give you the shot\n' +
        'When I vodka,'... 38723 more characters,
      expected: null
    },
    ExpectedConstraintError: Invalid string length
        at Object.run (/home/container/node_modules/@sapphire/shapeshift/dist/index.js:1546:79)
        at StringValidator.run (/home/container/node_modules/@sapphire/shapeshift/dist/index.js:202:27)
        at UnionValidator.handle (/home/container/node_modules/@sapphire/shapeshift/dist/index.js:1099:32)
        at UnionValidator.parse (/home/container/node_modules/@sapphire/shapeshift/dist/index.js:212:88)
        at EmbedBuilder.setDescription (/home/container/node_modules/@discordjs/builders/dist/index.js:319:26)
        at Client.<anonymous> (/home/container/src/poruEvents/trackStart.js:110:14)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      constraint: 's.string.lengthLessThanOrEqual',
      given: '[Intro: DJ Kay Slay & \n' +
        'Sheek Louch\n' +
        ']\n' +
        'Trackateering Music\n' +
        "Man, y'all did it with this one here, y'all\n" +
        `People love to use that quote, "I'm doin' it for the culture"\n` +
        "But what culture is that that you're talking about?\n" +
        'The one that you claim as a hip-hop artist\n' +
        "But won't do the research on hip-hop history\n" +
        'Or the one where you disrespect, disconnect\n' +
        'And disregard the founding fathers?\n' +
        "But you know what? Whatever it is, it don't even matter\n" +
        "'Cause as long as I'm alive\n" +
        "I'ma show and prove where this culture came from\n" +
        "And what it's really all about\n" +
        '\n' +
        'I got you, my nigga, yo, ayo\n' +
        '\n' +
        '[Verse 1: Sheek Louch]\n' +
        "Count to ten and then come in shootin'\n" +
        'Fuck peace, Silverback the new Huey Newton\n' +
        "I feel it, it's in the air, white cop with a stare\n" +
        "New judge in the chair, this shit hittin' the fan\n" +
        "But me, I'ma be smart and legalize my shit\n" +
        "And I ain't leavin' the house without that in my hand\n" +
        "And it ain't only the cops, it's niggas on your block\n" +
        "That talk like a lil' bitch and act like they your man\n" +
        '\n' +
        '[Verse 2: Styles P]\n' +
        "Somethin' like Kris Parker, my Uzi weigh a ton\n" +
        "Hundred niggas on the track, then you know I'll be the one\n" +
        'To tell niggas to suck cock, run and get a gun\n' +
        "It's old P, new P, prob'ly layin' in the sun\n" +
        "Prob'ly on a P.I., if I call you king\n" +
        "I ain't talkin' 'bout rap, nigga, that status go to B.I\n" +
        'You can fuck around and get burnt like a C.I\n' +
        'More bars than jail, nigga, who tryna get a V.I?[Verse 3: Dave East]\n' +
        'You dealing with stock owners, conversation with stockbrokers\n' +
        "Make a call for coco, smokin' dope from my crop grower\n" +
        'The block know us, kush got a funky sock odor\n' +
        'How could you not notice? I come from that rock culture (Rock)\n' +
        'Star of the squad but they cannot coach (At all)\n' +
        'Louis Vuitton holster, this for my niggas in the cell\n' +
        'And on they wall, they got a Nicki Minaj poster\n' +
        "The talk's over, no drive-by's, we walked over\n" +
        '\n' +
        '[Verse 4: KXNG Crooked]\n' +
        'COB bandana tied to the end of the AR\n' +
        "Iller than they are, rhymes so sick, give 'em the day off\n" +
        'This is the chaos, Nicolas Cage, face off\n' +
        "The dark knight, I make it a dark night when I'm gettin' that K off\n" +
        'Better than whoever done it, even officers better run it\n' +
        "With the drum, I got a technique that'll give twelve a hundred\n" +
        'Now the tables turn, to whom it may concern\n' +
        'I used to control more shooters than David Stern\n' +
        'With Lucifer, hater burn\n' +
        '\n' +
        '[Verse 5: Black Thought]\n' +
        'Yo, I was in the park spray-painting on the platform\n' +
        'Patent leather top ten, Space Invader hats on\n' +
        "Eighty something, I've been a threat for that long\n" +
        'Where a lot of people get poked up and clapped on\n' +
        'My job really putting on for the city\n' +
        'You get popped like a wheelie for saying some old silly shit\n' +
        "Tell me it'll be safer to say it in Swahili\n" +
        'They be wheeling you away if you say it in South Philly[Verse 6: Conway the Machine]\n' +
        "Look, thirty shots, I'm shootin' to peel his top\n" +
        "When them niggas sending shots, they shootin' to get the spot\n" +
        "That I'm in, nigga (Hahaha)\n" +
        'You know what it is when I spin the block (Ah)\n' +
        "Uppin' this Draco, the witness is still in shock (Brrr!)\n" +
        "Fluffin' a brick of this yayo, I tilt the pot (Whip)\n" +
        "Tuckin' this fifth, you play with me, you getting shot (Boom, boom, boom, boom)\n" +
        'Yeah, niggas still waiting for me to drop (Uh-huh)\n' +
        'I robbed niggas for they base and sold easy rock\n' +
        '\n' +
        '[Verse 7: Raekwon]\n' +
        '\n' +
        'Fur coats and magnums\n' +
        '\n' +
        'Come through the hall with the big blammers\n' +
        'Bentaygas parked, let me handle this\n' +
        "Jewelry that's flashy, jeans is a thousand, we slick nasty\n" +
        'Pull out a hundred in your housing\n' +
        "Yeah, it's raw lingo when the king go\n" +
        'Dutch link, nuts big as shit, taste the rainbow (Ayo, yo!)\n' +
        'Put your paper up and threaten shit\n' +
        'Or tie something up, send some messages\n' +
        '\n' +
        '[Verse 8: Ghostface Killah]\n' +
        'Ayo, ayo, I used to tell a maid, "Sunny side up"\n' +
        'Basement, a chainsaw, money tied up\n' +
        "Paper bag over his head, tell 'em come on, let the cries out\n" +
        'Wave a whole chicken by his legs near the crotch smells\n' +
        'Sweating bullets in the tip, blow torching his flesh\n' +
        'I seen his face melt, drip gooey shit on his chest\n' +
        'Watch this motherfucker beg for mercy\n' +
        'Shoulda let his wiz suck my dick for the time he jerked me[Verse 9: Inspectah Deck]\n' +
        'The soldier I rolls with the coldest clique\n' +
        'Call me prototype, never had a mold to fit\n' +
        'My clothes is dipped, my bros is lit\n' +
        'Only time you been sick is when the COVID hit\n' +
        "Better get in line, I chop the bass like I'm pitching dimes\n" +
        'Code name Coffee Bean how I hit the grind\n' +
        'Precision design, exquisite with the vivid shine\n' +
        "I'm like a European watch on a different time\n" +
        '\n' +
        '[Verse 10: Papoose]\n' +
        'I used to run around with a MAC-10\n' +
        'Back when I was 20 years old, that was back then (30)\n' +
        '30 clip in the 40, move yayo like 50\n' +
        'Man, I hustle like Nip in the Rolling 60s\n' +
        "I was born in the 70's, grew up in the 80's\n" +
        'Got the MAC-90, then I went crazy\n' +
        "Do the mathematics, y'all can't compete (100)\n" +
        "All by myself, I'm 100 deep\n" +
        '\n' +
        '[Verse 11: Loaded Lux]\n' +
        'I was on the first 50, now the powers at a dollar\n' +
        'Politician pushing tracks in it, mayor, I president in it\n' +
        "Til it's humbling, think you grounded and get punished\n" +
        'This the second time Slay needed my two cents to keep it a hundred\n' +
        'How you want it? Fake and be a martyr for this matrix?\n' +
        'They gon turn up the AC then charge you for the blankets\n' +
        'Lux verse mean, got you stuck standing there\n' +
        'Like you at a stop sign waiting for it to turn green, what you mean?\n' +
        '\n' +
        '[Verse 12: AZ]\n' +
        'My soul is never for sale\n' +
        "My youngin' just did a twelve, he home, he ringing bells\n" +
        'Wish him well, me and mines on different times\n' +
        "Decline from nigga crimes, I'm fine just spitting rhymes\n" +
        'Read the signs, body language is loud\n' +
        "Cowards hang with the crowd, I ain't never changing my style\n" +
        'Then and now, before that was all that\n' +
        'Fall back, official is what you call that\n' +
        '\n' +
        '[Verse 13: Bun B]\n' +
        'I be that Third Coast legend, Dirty South icon\n' +
        "Shuttin' shit down, soon as they cut my mic on\n" +
        'From the first bar down to the last syllable\n' +
        'Niggas that thought they were immortal find out they killable\n' +
        "Once I see blood, I'm like a Great White\n" +
        "Catch you slippin' on a late night and it's no bark, straight bite\n" +
        'Watch you bleed out as reality starts to sink in\n' +
        'You tried the Triple OG (Bitch) what was you thinking?\n' +
        '\n' +
        '[Verse 14: Fred the Godson]\n' +
        "I give the coke to your crew, the butter's crazy\n" +
        'Fallopian tube, just cut it baby\n' +
        'Gordo butterfly collar cover the Cubans\n' +
        "She need pads like Ewing, I hope you know what you doin' (Look)\n" +
        'Some paid 4-5 serious\n' +
        'I come through, 4-5, serious\n' +
        'Slay got me Shade 45 Sirius\n' +
        'Gold frame shades 45, Siri\n' +
        '\n' +
        '[Verse 15: Jim Jones]\n' +
        'I used to be up in a tunnel like a hundred deep\n' +
        `Screamin', "Nine Trey, Su-Woo" with a bunch of Bs\n` +
        'Never tied up shoes, but every night we would run the streets\n' +
        "Nigga, fuck growlin', it was nights I heard my stomach speak\n" +
        "Then I started pumpin' that bass like they done a beat\n" +
        "Never let shit slide 'cause they might think somethin' sweet\n" +
        "Nigga, it's July, shots get hot like summer heat\n" +
        'When I pop up, niggas turn vegan, they never wanted beef\n' +
        '\n' +
        '[Verse 16: Ransom]\n' +
        'I know these streets with my eyes closed, so my worst fear is to die slow\n' +
        "Lie low, 'cause in '05 you flipped the five-o\n" +
        "And I know, 'cause if Alpo did it to Rich\n" +
        "For some bricks, word to Flex, he had no reason to lie, po'\n" +
        "Aight though, we ain't gotta dwell on the past\n" +
        "Devilish laugh, arrow spins I'm ahead of the crash\n" +
        'Better to clash, when you handle your beef, settle it fast\n' +
        'Metal in mask but still keep an elegant class\n' +
        '\n' +
        '[Verse 17: Rah Digga]\n' +
        'Who the greatest all time? Where them niggas reside?\n' +
        'I seen all fifty names, man them niggas done lied\n' +
        'I take the first forty-eight, make them niggas retire\n' +
        'Last two we could joust, make them niggas my squad\n' +
        "Fuck them, let's see how the ladies fare\n" +
        "Swerve on these bitches like I'm settin' my baby hair\n" +
        "They feel a type way, but they never gon' take it there\n" +
        "They tryna keep it cute 'cause they know that it's safer there\n" +
        "They wouldn't dare\n" +
        '\n' +
        '[Verse 18: Billy Danze]\n' +
        "I can't explain what I dealt with\n" +
        'Know it was all weak and creep and stealth shit\n' +
        'When I come from under the belt with a metal shit\n' +
        "Forever Brownsville, no, I never felt shit (You're as cold as ice)\n" +
        'I still got that real world charm, nigga, be alarmed\n' +
        'Body armor on, warmer in my palm (NYC)\n' +
        'Where you get the storm before the calm\n' +
        'OG and we treat it like Vietnam\n' +
        '\n' +
        '[Verse 19: Lil Fame]\n' +
        'My generation drank forty ounces of Old English to ease the pain\n' +
        "Y'all niggas drink White Claws, nigga, we ain't the same (kahm-kahm)\n" +
        "It's curfew whenever I come through (kahm-kahm)\n" +
        "Kill the fuckery, them niggas can't fuck with me (come on!)\n" +
        "I'm really 'bout it in the war\n" +
        "Taxiderm' your bitch head, mount it on the wall (it's M.O.)\n" +
        "Throw it up, nigga, we stand tall (it's M.O.)\n" +
        "You know what the fuck we stand for, it's M.O\n" +
        '\n' +
        '[Verse 20: Trae the Truth]\n' +
        'Too many niggas in here, but never follow the script\n' +
        "It's movie time, release the clip and have 'em doin' a flip\n" +
        'Off-white Virgil, need a whip with the interior Crip\n' +
        'On any given goal to slide, nigga, minus the slip\n' +
        "Checkin' niggas outta line, like it ain't nothin' to skip\n" +
        "Step in my section trying to flex and end up gettin' you stripped\n" +
        'Too many niggas watered down, might go to sinking they ship\n' +
        "And if it's beef, I cut the trip, I never pull up and dip\n" +
        "It's Precious season, nigga\n" +
        '\n' +
        '[Verse 21: Joell Ortiz]\n' +
        "Walkin' in the storm, my face had the hatred in it\n" +
        'Mons had the colorful money with the staples in it\n' +
        'Grew up street and I stay committed (Yeah)\n' +
        "Movin' white back and forth over green like table tennis\n" +
        "Guap was pourin' in, my Glock was roarin'\n" +
        'At nineteen, shots hit you like hydroxychloroquine\n' +
        "I'm still forty with the forty close\n" +
        "In the 840 playin' new E-40 with some horny hoes\n" +
        '\n' +
        '[Verse 22: Lord Tariq]\n' +
        "(Yeah) Finally, y'all been waiting\n" +
        'To hear a verse for the economy stimulation\n' +
        'With Bible verses forsaken and tribal authorization\n' +
        "We marchin' as we awaken the mobsters across the nation\n" +
        'Ask doubles next to ride\n' +
        'The show gun with Shogun to testify\n' +
        "To show somethin', we hold somethin' that electrifies\n" +
        'N-1 L-B, no one left behind, pause it\n' +
        '\n' +
        '[Verse 23: Cory Gunz]\n' +
        'Where I grew up in the world of Pop to give you the shot\n' +
        'When I vodka,'... 38723 more characters,
      expected: 'expected.length <= 4096'
    }
  ]
}

**Comment by Grimfoxy19883** [comment]
this isn't even the right lyrics.

**Comment by AliAryanTech** [comment]
> this isn't even the right lyrics.

Sorry, for late reply but can you give the url and tell what you expecting to happen
